/*
 * apimaticcalculator
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */

package apimaticcalculator

/** The base Uri for API calls */
const BASEURI string = "https://examples.apimatic.io/apps/calculator"

